#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;
use Log::ger; BEGIN { $ENV{LOG_LEVEL} //= 'info' }

use Perinci::CmdLine::Any;

my $prefix = "/App/swcat/";

my $cli = Perinci::CmdLine::Any->new(
    url => $prefix,
    log => 1,
    subcommands => {
        'list' => {url=>"${prefix}list"},
        'latest-version' => {url=>"${prefix}latest_version"},
        'available-versions' => {url=>"${prefix}available_versions"},
        'download-url' => {url=>"${prefix}download_url"},
        'release-note' => {url=>"${prefix}release_note"},
        'archive-info' => {url=>"${prefix}archive_info"},
    },
);
$cli->run;

# ABSTRACT: Software catalog
# PODNAME:

=head1 SYNOPSIS

 # list known software
 % swcat list
 % swcat list -l  ;# detail

 # get latest version of a software
 % swcat latest-version firefox  ;# by default will be cached for a day
 % swcat latest-version firefox --no-cache

 # get latest version of a few software
 % swcat latest-version firefox seamonkey

 # get latest version of all known software
 % swcat latest-version

 # get latest version of known software matching a regex
 % swcat latest-version /fire|sea/

 # get list of available versions of a software
 % swcat available-versions bulwark-qt

 # get release note for the latest version of a software
 % swcat release-note bulwark-qt

 # get release note for a version of a software
 % swcat release-note bulwark-qt 1.3.0

 # get download URL(s) of a software
 % swcat download-url firefox
 % swcat download-url firefox --arch win32


=head1 SEE ALSO

L<Software::Catalog>

L<App::SoftwareCatalogUtils>

L<instopt> from L<App::instopt>
