#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;
use Log::ger; BEGIN { $ENV{LOG_LEVEL} //= 'info' }

use Perinci::CmdLine::Any;

my $prefix = "/App/swcat/";

my $cli = Perinci::CmdLine::Any->new(
    url => $prefix,
    log => 1,
    subcommands => {
        'list' => {url=>"${prefix}list"},
        'latest-version' => {url=>"${prefix}latest_version"},
        'download-url' => {url=>"${prefix}download_url"},
        'download' => {url=>"${prefix}download"},
    },
);
$cli->run;

# ABSTRACT: Software catalog
# PODNAME:

=head1 SYNOPSIS

In F<~/.config/swcat.conf>:

 ; if not specified, defaults to ~/archive
 archive_dir = /media/software

Then:

 # list known software
 % swcat list
 % swcat list -l  ;# detail

 # get latest version of a software
 % swcat latest-version firefox  ;# by default will be cached for a day
 % swcat latest-version firefox --no-cache

 # get download URL(s) of a software
 % swcat download-url firefox
 % swcat download-url firefox --arch win32

 # download latest version of a software (to $archive_dir/f/firefox/$ver/$arch/)
 % swcat download firefox


=head1 SEE ALSO

L<Software::Catalog>

L<App::SoftwareCatalogUtils>

L<instopt> from L<App::instopt>
